
FROM node:20-alpine AS builder

WORKDIR /app


COPY package*.json ./


RUN npm ci


COPY . .
RUN npx prisma generate


RUN npm run build


RUN npm prune --production

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production




COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts /app/


COPY entrypoint.sh /usr/bin/entrypoint.sh

RUN chmod +x /usr/bin/entrypoint.sh


RUN mkdir -p app/Uploads
RUN chown -R node:node app/Uploads

ENTRYPOINT ["entrypoint.sh"]
EXPOSE 8080



CMD ["node", "dist/src/main.js"]