/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Team Forge API
 * Team forge API desc
 * OpenAPI spec version: 1.0
 */
export type PlayerAddRequestEmail = { [key: string]: unknown };

/**
 * @minLength 6
 */
export type PlayerAddRequestPassword = { [key: string]: unknown };

export interface PlayerAddRequest {
  email: PlayerAddRequestEmail;
  /** @minLength 6 */
  password: PlayerAddRequestPassword;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface FaceitSegmentStats {
  mapName: string;
  imgRegular: string;
  matches: number;
  winRate: string;
  kdRatio: string;
  wins: number;
  triples: string;
  adr: string;
}

export interface FaceitStatsDto {
  faceitId: string;
  kdRatio: string;
  matches: number;
  winRate: string;
  avg: number;
  currentWinStreak: string;
  longestWinStreak: string;
  adr: string;
  segmentStats: FaceitSegmentStats[];
}

export interface FaceitUserResponse {
  nickname: string;
  avatar?: string;
  elo: number;
  country: string;
  skillLevel: number;
}

export type TeamResponseId = { [key: string]: unknown };

export type TeamResponseName = { [key: string]: unknown };

export interface TeamResponse {
  id: TeamResponseId;
  name: TeamResponseName;
  players: PlayerResponse[];
  captain: PlayerResponse;
  canEdit: boolean;
  avatar: string;
}

export type PlayerResponseId = { [key: string]: unknown };

export type PlayerResponseEmail = { [key: string]: unknown };

export type PlayerResponsePassword = { [key: string]: unknown };

export type PlayerResponseTeamId = { [key: string]: unknown };

export interface PlayerResponse {
  id: PlayerResponseId;
  email: PlayerResponseEmail;
  password: PlayerResponsePassword;
  createdAt: string;
  updatedAt: string;
  teamId: PlayerResponseTeamId;
  faceitProfile?: FaceitUserResponse;
  team: TeamResponse;
}

export interface TeamCreateRequest {
  name: string;
  description?: string;
}

export type TournamentRegisterRequestTitle = { [key: string]: unknown };

export type TournamentRegisterRequestType = { [key: string]: unknown };

export interface TournamentRegisterRequest {
  title: TournamentRegisterRequestTitle;
  startTime: string;
  endTime: string;
  type: TournamentRegisterRequestType;
}

export type MatchRegisterRequestMatchType = { [key: string]: unknown };

export type MatchRegisterRequestTeamAId = { [key: string]: unknown };

export type MatchRegisterRequestTeamBId = { [key: string]: unknown };

export type MatchRegisterRequestTournamentId = { [key: string]: unknown };

export interface MatchRegisterRequest {
  matchType: MatchRegisterRequestMatchType;
  teamAId: MatchRegisterRequestTeamAId;
  teamBId: MatchRegisterRequestTeamBId;
  tournamentId?: MatchRegisterRequestTournamentId;
  startTime?: string;
}

export type MatchResponseId = { [key: string]: unknown };

export type MatchResponseMatchType = { [key: string]: unknown };

/**
 * @nullable
 */
export type MatchResponseTournamentId = { [key: string]: unknown } | null;

export type MatchResponseTeamAId = { [key: string]: unknown };

export type MatchResponseTeamBId = { [key: string]: unknown };

/**
 * @nullable
 */
export type MatchResponseTournament = TournamentResponse | null;

export interface MatchResponse {
  id: MatchResponseId;
  matchType: MatchResponseMatchType;
  /** @nullable */
  tournamentId: MatchResponseTournamentId;
  teamAId: MatchResponseTeamAId;
  teamBId: MatchResponseTeamBId;
  /** @nullable */
  tournament: MatchResponseTournament;
  teamA: TeamResponse;
  teamB: TeamResponse;
  /** @nullable */
  startTime: string | null;
  createdAt: string;
  updatedAt: string;
}

export type TournamentMembersResId = { [key: string]: unknown };

export type TournamentMembersResTeamId = { [key: string]: unknown };

export type TournamentMembersResTournamentId = { [key: string]: unknown };

export interface TournamentMembersRes {
  id: TournamentMembersResId;
  teamId: TournamentMembersResTeamId;
  TournamentId: TournamentMembersResTournamentId;
  Tournament: TournamentResponse;
  Team: TeamResponse;
  createdAt: string;
  updatedAt: string;
}

export type TournamentResponseId = { [key: string]: unknown };

export type TournamentResponseTitle = { [key: string]: unknown };

export type TournamentResponseType = { [key: string]: unknown };

export interface TournamentResponse {
  id: TournamentResponseId;
  title: TournamentResponseTitle;
  startTime: string;
  endTime: string;
  type: TournamentResponseType;
  mathes: MatchResponse[];
  teams: TournamentMembersRes[];
}

export interface RoleDto {
  id: string;
  name: string;
}

export type ResumeResponseType = { [key: string]: unknown };

export interface ResumeResponse {
  description: string;
  type: ResumeResponseType;
  language: string;
  roles: RoleDto[];
  player: PlayerResponse;
}

export type ResumeRegisterRequestType = { [key: string]: unknown };

export interface ResumeRegisterRequest {
  description: string;
  type: ResumeRegisterRequestType;
  language: string;
  roles: string[];
}

export type PlayerControllerGetUserData200 = { [key: string]: unknown };

export type PlayerControllerGetById200 = { [key: string]: unknown };

export type FaceitControllerLoginCallbackParams = {
code: string;
};

export type TeamControllerGetTeamByNameParams = {
q: string;
};

export type TeamControllerDeleteTeam200 = { [key: string]: unknown };

export type TournamentControllerGetTournament200 = { [key: string]: unknown };

export type MatchControllerGetMatch200 = { [key: string]: unknown };

