/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Team Forge API
 * Team forge API desc
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequest,
  MatchControllerGetMatch200,
  MatchRegisterRequest,
  MatchResponse,
  PlayerAddRequest,
  PlayerControllerGetById200,
  PlayerControllerLogin201,
  TeamControllerDeleteTeam200,
  TeamControllerGetTeamByNameParams,
  TeamCreateRequest,
  TeamResponse,
  TournamentControllerGetTournament200,
  TournamentRegisterRequest
} from './generated.schemas';




  export const getTeamForgeAPI = () => {
const appControllerGetHello = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/`,{
        responseType: 'text',
    ...options,}
    );
  }

const appControllerGetBye = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/bye`,{
        responseType: 'text',
    ...options,}
    );
  }

const playerControllerGetById = <TData = AxiosResponse<PlayerControllerGetById200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Player/${id}`,options
    );
  }

const playerControllerRegister = <TData = AxiosResponse<void>>(
    playerAddRequest: PlayerAddRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Player`,
      playerAddRequest,options
    );
  }

const playerControllerLogin = <TData = AxiosResponse<PlayerControllerLogin201>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Player/login`,
      loginRequest,options
    );
  }

const teamControllerGetTeamByName = <TData = AxiosResponse<TeamResponse[]>>(
    params: TeamControllerGetTeamByNameParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Team`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const teamControllerRegisterTeam = <TData = AxiosResponse<TeamResponse>>(
    teamCreateRequest: TeamCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Team`,
      teamCreateRequest,options
    );
  }

const teamControllerGetTeam = <TData = AxiosResponse<TeamResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Team/${id}`,options
    );
  }

const teamControllerDeleteTeam = <TData = AxiosResponse<TeamControllerDeleteTeam200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/Team/${id}`,options
    );
  }

const tournamentControllerGetTournament = <TData = AxiosResponse<TournamentControllerGetTournament200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Tournament/${id}`,options
    );
  }

const tournamentControllerAddTournament = <TData = AxiosResponse<void>>(
    tournamentRegisterRequest: TournamentRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Tournament`,
      tournamentRegisterRequest,options
    );
  }

const matchControllerGetMatch = <TData = AxiosResponse<MatchControllerGetMatch200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Match/${id}`,options
    );
  }

const matchControllerDeleteMatch = <TData = AxiosResponse<MatchResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/Match/${id}`,options
    );
  }

const matchControllerRegisterMatch = <TData = AxiosResponse<void>>(
    matchRegisterRequest: MatchRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Match`,
      matchRegisterRequest,options
    );
  }

return {appControllerGetHello,appControllerGetBye,playerControllerGetById,playerControllerRegister,playerControllerLogin,teamControllerGetTeamByName,teamControllerRegisterTeam,teamControllerGetTeam,teamControllerDeleteTeam,tournamentControllerGetTournament,tournamentControllerAddTournament,matchControllerGetMatch,matchControllerDeleteMatch,matchControllerRegisterMatch}};
export type AppControllerGetHelloResult = AxiosResponse<string>
export type AppControllerGetByeResult = AxiosResponse<string>
export type PlayerControllerGetByIdResult = AxiosResponse<PlayerControllerGetById200>
export type PlayerControllerRegisterResult = AxiosResponse<void>
export type PlayerControllerLoginResult = AxiosResponse<PlayerControllerLogin201>
export type TeamControllerGetTeamByNameResult = AxiosResponse<TeamResponse[]>
export type TeamControllerRegisterTeamResult = AxiosResponse<TeamResponse>
export type TeamControllerGetTeamResult = AxiosResponse<TeamResponse>
export type TeamControllerDeleteTeamResult = AxiosResponse<TeamControllerDeleteTeam200>
export type TournamentControllerGetTournamentResult = AxiosResponse<TournamentControllerGetTournament200>
export type TournamentControllerAddTournamentResult = AxiosResponse<void>
export type MatchControllerGetMatchResult = AxiosResponse<MatchControllerGetMatch200>
export type MatchControllerDeleteMatchResult = AxiosResponse<MatchResponse>
export type MatchControllerRegisterMatchResult = AxiosResponse<void>
