/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Team Forge API
 * Team forge API desc
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  FaceitControllerLoginCallbackParams,
  FaceitStatsDto,
  LoginRequest,
  MatchControllerGetMatch200,
  MatchRegisterRequest,
  MatchResponse,
  PlayerAddRequest,
  PlayerControllerGetById200,
  PlayerControllerGetUserData200,
  ResumeRegisterRequest,
  ResumeResponse,
  RoleDto,
  TeamControllerDeleteTeam200,
  TeamControllerGetTeamByNameParams,
  TeamCreateRequest,
  TeamResponse,
  TournamentControllerGetTournament200,
  TournamentRegisterRequest
} from './generated.schemas';




  export const getTeamForgeAPI = () => {
const appControllerGetHello = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/`,{
        responseType: 'text',
    ...options,}
    );
  }

const appControllerGetBye = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/bye`,{
        responseType: 'text',
    ...options,}
    );
  }

const playerControllerFaceitLogin = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Player/faceit`,options
    );
  }

const playerControllerGetUserData = <TData = AxiosResponse<PlayerControllerGetUserData200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Player/me`,options
    );
  }

const playerControllerGetById = <TData = AxiosResponse<PlayerControllerGetById200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Player/${id}`,options
    );
  }

const playerControllerRegister = <TData = AxiosResponse<void>>(
    playerAddRequest: PlayerAddRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Player`,
      playerAddRequest,options
    );
  }

const playerControllerLogin = <TData = AxiosResponse<void>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Player/login`,
      loginRequest,options
    );
  }

const faceitControllerGetStats = <TData = AxiosResponse<FaceitStatsDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/faceit/me/stats`,options
    );
  }

const faceitControllerGetStatsById = <TData = AxiosResponse<FaceitStatsDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/faceit/stats/${id}`,options
    );
  }

const faceitControllerFaceitLogin = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/faceit`,options
    );
  }

const faceitControllerLoginCallback = <TData = AxiosResponse<void>>(
    params: FaceitControllerLoginCallbackParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/faceit/callback`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const teamControllerGetTeamByName = <TData = AxiosResponse<TeamResponse[]>>(
    params: TeamControllerGetTeamByNameParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Team`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const teamControllerRegisterTeam = <TData = AxiosResponse<TeamResponse>>(
    teamCreateRequest: TeamCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Team`,
      teamCreateRequest,options
    );
  }

const teamControllerGetTeam = <TData = AxiosResponse<TeamResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Team/${id}`,options
    );
  }

const teamControllerDeleteTeam = <TData = AxiosResponse<TeamControllerDeleteTeam200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/Team/${id}`,options
    );
  }

const tournamentControllerGetTournament = <TData = AxiosResponse<TournamentControllerGetTournament200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Tournament/${id}`,options
    );
  }

const tournamentControllerAddTournament = <TData = AxiosResponse<void>>(
    tournamentRegisterRequest: TournamentRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Tournament`,
      tournamentRegisterRequest,options
    );
  }

const matchControllerGetMatch = <TData = AxiosResponse<MatchControllerGetMatch200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/Match/${id}`,options
    );
  }

const matchControllerDeleteMatch = <TData = AxiosResponse<MatchResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/Match/${id}`,options
    );
  }

const matchControllerRegisterMatch = <TData = AxiosResponse<void>>(
    matchRegisterRequest: MatchRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/Match`,
      matchRegisterRequest,options
    );
  }

const resumeControllerGetResumes = <TData = AxiosResponse<ResumeResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/resume`,options
    );
  }

const resumeControllerRegisterResume = <TData = AxiosResponse<ResumeResponse>>(
    resumeRegisterRequest: ResumeRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/resume`,
      resumeRegisterRequest,options
    );
  }

const resumeControllerGetRoles = <TData = AxiosResponse<RoleDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/resume/roles`,options
    );
  }

return {appControllerGetHello,appControllerGetBye,playerControllerFaceitLogin,playerControllerGetUserData,playerControllerGetById,playerControllerRegister,playerControllerLogin,faceitControllerGetStats,faceitControllerGetStatsById,faceitControllerFaceitLogin,faceitControllerLoginCallback,teamControllerGetTeamByName,teamControllerRegisterTeam,teamControllerGetTeam,teamControllerDeleteTeam,tournamentControllerGetTournament,tournamentControllerAddTournament,matchControllerGetMatch,matchControllerDeleteMatch,matchControllerRegisterMatch,resumeControllerGetResumes,resumeControllerRegisterResume,resumeControllerGetRoles}};
export type AppControllerGetHelloResult = AxiosResponse<string>
export type AppControllerGetByeResult = AxiosResponse<string>
export type PlayerControllerFaceitLoginResult = AxiosResponse<void>
export type PlayerControllerGetUserDataResult = AxiosResponse<PlayerControllerGetUserData200>
export type PlayerControllerGetByIdResult = AxiosResponse<PlayerControllerGetById200>
export type PlayerControllerRegisterResult = AxiosResponse<void>
export type PlayerControllerLoginResult = AxiosResponse<void>
export type FaceitControllerGetStatsResult = AxiosResponse<FaceitStatsDto>
export type FaceitControllerGetStatsByIdResult = AxiosResponse<FaceitStatsDto>
export type FaceitControllerFaceitLoginResult = AxiosResponse<void>
export type FaceitControllerLoginCallbackResult = AxiosResponse<void>
export type TeamControllerGetTeamByNameResult = AxiosResponse<TeamResponse[]>
export type TeamControllerRegisterTeamResult = AxiosResponse<TeamResponse>
export type TeamControllerGetTeamResult = AxiosResponse<TeamResponse>
export type TeamControllerDeleteTeamResult = AxiosResponse<TeamControllerDeleteTeam200>
export type TournamentControllerGetTournamentResult = AxiosResponse<TournamentControllerGetTournament200>
export type TournamentControllerAddTournamentResult = AxiosResponse<void>
export type MatchControllerGetMatchResult = AxiosResponse<MatchControllerGetMatch200>
export type MatchControllerDeleteMatchResult = AxiosResponse<MatchResponse>
export type MatchControllerRegisterMatchResult = AxiosResponse<void>
export type ResumeControllerGetResumesResult = AxiosResponse<ResumeResponse[]>
export type ResumeControllerRegisterResumeResult = AxiosResponse<ResumeResponse>
export type ResumeControllerGetRolesResult = AxiosResponse<RoleDto[]>
